# Generated by Django 4.2.20 on 2025-05-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='pelanggaran/')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('lokasi', models.CharField(max_length=100)),
                ('plat_nomor', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
