# Generated by Django 4.2.20 on 2025-05-22 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id_kendaraan', models.AutoField(primary_key=True, serialize=False)),
                ('plat_nomor', models.CharField(max_length=15)),
                ('jenis_kendaraan', models.CharField(max_length=50)),
                ('foto_kendaraan', models.ImageField(upload_to='kendaraan/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggaran',
            fields=[
                ('id_pelanggaran', models.AutoField(primary_key=True, serialize=False)),
                ('waktu', models.DateTimeField()),
                ('lokasi', models.CharField(max_length=200)),
                ('bukti_gambar', models.ImageField(upload_to='pelanggaran/')),
                ('status', models.CharField(max_length=50)),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halaman.kendaraan')),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_baca', models.BooleanField(default=False)),
                ('metode', models.CharField(max_length=50)),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifikasi_admin', to=settings.AUTH_USER_MODEL)),
                ('pelanggaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halaman.pelanggaran')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
