# Generated by Django 4.2.20 on 2025-06-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0003_alter_pelanggaran_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Nonaktif', 'Nonaktif')], default='Aktif', max_length=10)),
                ('waktu_ditambahkan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
