# Generated by Django 4.2.20 on 2025-06-14 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0004_kamera'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggaran',
            name='kamera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akun.kamera'),
        ),
    ]
