# Generated by Django 4.2.10 on 2025-06-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0005_pelanggaran_kamera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggaran',
            name='bukti_gambar',
        ),
        migrations.RemoveField(
            model_name='pelanggaran',
            name='kendaraan',
        ),
        migrations.AddField(
            model_name='pelanggaran',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pelanggaran',
            name='image_base64',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pelanggaran',
            name='plate_number',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='pelanggaran',
            name='status',
            field=models.CharField(choices=[('Belum Ditindak', 'Belum Ditindak'), ('Ditindak', 'Ditindak'), ('Selesai', 'Selesai')], default='Belum Ditindak', max_length=20),
        ),
    ]
