# Generated by Django 4.2.10 on 2025-06-30 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0006_remove_pelanggaran_bukti_gambar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggaran',
            name='kendaraan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akun.kendaraan'),
        ),
    ]
