# Generated by Django 4.2.10 on 2025-07-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0007_pelanggaran_kendaraan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggaran',
            name='jumlah_denda',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=10),
        ),
    ]
