# Generated by Django 4.2.20 on 2025-07-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0008_pelanggaran_jumlah_denda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggaran',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/'),
        ),
    ]
