# Generated by Django 4.2.20 on 2025-07-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0009_pelanggaran_bukti_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggaran',
            name='status',
            field=models.CharField(choices=[('Belum Ditindak', 'Belum Ditindak'), ('Ditindak', 'Ditindak'), ('Menunggu Verifikasi', 'Menunggu Verifikasi'), ('Selesai', 'Selesai')], default='Belum Ditindak', max_length=20),
        ),
    ]
