# Generated by Django 4.2.10 on 2025-07-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0010_alter_pelanggaran_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nim',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
