# Generated by Django 4.2.20 on 2025-06-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggaran',
            name='status',
            field=models.CharField(choices=[('Belum Ditindak', 'Belum Ditindak'), ('Ditindak', 'Ditindak'), ('Selesai', 'Selesai')], max_length=20),
        ),
    ]
